/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f9ff',
        'error-container': '#ffdad6',
        'surface-tint': '#435b9f',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#2a4386',
        'on-background': '#0b1c30',
        'tertiary-container': '#002560',
        'surface-technical': '#F8FAFC',
        'secondary-fixed-dim': '#ffb596',
        'on-secondary-fixed-variant': '#7c2e00',
        'secondary': '#a33e00',
        'border-muted': '#E2E8F0',
        'on-surface': '#0b1c30',
        'surface-container-high': '#dce9ff',
        'primary-container': '#002366',
        'inverse-on-surface': '#eaf1ff',
        'background': '#f8f9ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-surface-variant': '#444650',
        'tertiary': '#001237',
        'on-tertiary': '#ffffff',
        'success-electric': '#10B981',
        'error': '#ba1a1a',
        'on-primary-container': '#758dd5',
        'secondary-container': '#fe6500',
        'secondary-fixed': '#ffdbcd',
        'on-secondary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#00419e',
        'text-heading': '#0F172A',
        'surface-container': '#e5eeff',
        'on-error': '#ffffff',
        'tertiary-fixed': '#dae2ff',
        'outline': '#757682',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#b1c5ff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface': '#f8f9ff',
        'inverse-primary': '#b3c5ff',
        'on-secondary-container': '#541d00',
        'outline-variant': '#c5c6d2',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'primary': '#00113a',
        'on-tertiary-container': '#5f8cf3',
        'inverse-surface': '#213145',
        'on-tertiary-fixed': '#001946',
        'on-primary-fixed': '#00174a',
        'surface-dim': '#cbdbf5',
        'surface-container-low': '#eff4ff',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'container-max': '1280px',
        'unit': '4px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'display': ['Montserrat', 'sans-serif'],
        'heading': ['Montserrat', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(0, 35, 102, 0.05)',
        'overlay': '0px 10px 30px rgba(0, 35, 102, 0.12)',
        'nav': '0 1px 3px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
}
